test:
  # v1 syntax
  build: .
  dockerfile: Dockerfile-test
  extends:
    file: docker-compose.yml
    service: nanodesign
  command:
    /nanodesign/tests/run_tests.sh


test-jenkins:
  # v1 syntax
  build: .
  dockerfile: Dockerfile-test
  extends:
    file: docker-compose.yml
    service: nanodesign
  volumes:
    - ./:/outputs
  environment:
    # path relative to inside the continer. real loation is mapped via volume statement
    OUTPUT_DIR: /outputs/
  command:
    /nanodesign/tests/run_tests_jenkins.sh
